### ISSUE TITLE
push snapshots to snapshots repository

### ISSUE THREAD

**Issue by glenlovett** [jmpage/capistrano_scm_nexus#2]
Instead of pushing snapshots to the releases path, we should push them to /snapshots

The name of the file then could be non-unique. I'm thinking we could just make new tasks to create/upload new snapshots, so that the user can enter the version: `rake 'snapshot:create[1.0.0]'` `rake 'snapshot:upload[1.0.0]'`

**Comment by vazw** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
asaddoost, @skyrpex, @this-is-mike, @oliver-soeser, @vanxining, @shai-almog, @pixlcrashr, @oreillyross, @St0nersdash, @Colstuwjx, @pyrocat101, @NanWuIT, @tkersey, @Tellexxii, @mattlinares, @shaqque, @mohammed-b-hassan, @studiolathe, @jeevaprakashdr, @Siedlerchr

**Comment by vazw** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
razdvapoka, @luxifer, @sebpalluel, @Prajnadeep, @creepyfemur666, @providenz, @jsor, @anatolinicolae, @labeldevops, @monil, @xmonader, @wangfei1981, @AliochaFilipovitch, @ryloric, @tomncooper, @diegov, @toto, @thomas-kl1, @spacecowb0y, @sansan88

**Comment by pixlcrashr** [comment]
@vazw 
Since when is phishing/spam a thing on GitHub?

@luxifer, @sebpalluel, @Prajnadeep, @creepyfemur666, @providenz, @jsor, @anatolinicolae, @labeldevops, @monil, @xmonader, @wangfei1981, @AliochaFilipovitch, @ryloric, @tomncooper, @diegov, @toto, @thomas-kl1, @spacecowb0y, @sansan88, @skyrpex, @this-is-mike, @oliver-soeser, @vanxining, @shai-almog, @oreillyross, @St0nersdash, @Colstuwjx, @pyrocat101, @NanWuIT, @tkersey, @Tellexxii, @mattlinares, @shaqque, @mohammed-b-hassan, @studiolathe, @jeevaprakashdr, @Siedlerchr

**Comment by jmpage** [comment]
It looks like either the person who posted the phishing spam has removed it or Github has. I'm going to close this issue as this repository is not actively being developed.
